- logs/ushop/cancel.json
- logs/ushop/search.json
- logs/ushop/searchbycity.json
- logs/ushop/select.json
> Updated ushop logs

- logs/Shiprocket-nstore/cancel.txt
- logs/Shiprocket-nstore/confirm.txt
- logs/Shiprocket-nstore/init.txt
- logs/Shiprocket-nstore/on_cancel.txt
- logs/Shiprocket-nstore/on_confirm.txt
- logs/Shiprocket-nstore/on_init.txt
- logs/Shiprocket-nstore/on_search.txt
- logs/Shiprocket-nstore/on_status.txt
- logs/Shiprocket-nstore/on_track.txt
- logs/Shiprocket-nstore/on_update.txt
- logs/Shiprocket-nstore/search.txt
- logs/Shiprocket-nstore/status.txt
- logs/Shiprocket-nstore/track.txt
- logs/Shiprocket-nstore/update.txt
Shiprocket integration testing with nstore
> add nstore intargration testing log

- logs/grab/confirm.log
- logs/grab/init.log
- logs/grab/search.log
- logs/grab/status.log
- logs/grab/track.log
- logs/grab/update.log
Grab Pre prod Logs - E2E with Nstore
> Grab - NStore E2E testing logs

- logs/Mystore/search-on_search--4f23f224-d65d-4d0c-aaf3-e1210f0a9999/4f23f224-d65d-4d0c-aaf3-e1210f0a9999_on_search (1).json
- logs/Mystore/search-on_search--4f23f224-d65d-4d0c-aaf3-e1210f0a9999/4f23f224-d65d-4d0c-aaf3-e1210f0a9999_on_search (2).json
- logs/Mystore/search-on_search--4f23f224-d65d-4d0c-aaf3-e1210f0a9999/4f23f224-d65d-4d0c-aaf3-e1210f0a9999_on_search (3).json
- logs/Mystore/search-on_search--4f23f224-d65d-4d0c-aaf3-e1210f0a9999/4f23f224-d65d-4d0c-aaf3-e1210f0a9999_on_search.json
- logs/Mystore/search-on_search--4f23f224-d65d-4d0c-aaf3-e1210f0a9999/4f23f224-d65d-4d0c-aaf3-e1210f0a9999_search.json
- logs/Mystore/search-on_search--4f23f224-d65d-4d0c-aaf3-e1210f0a9999/Readme
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/Readme
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_cancel.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_confirm.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_init.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_on_cancel.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_on_confirm.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_on_init.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_on_select.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--aa9d9997-631d-4e94-b772-91e2bc54176d/aa9d9997-631d-4e94-b772-91e2bc54176d_select.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/Readme
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_cancel.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_confirm.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_init.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_on_cancel.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_on_confirm.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_on_init.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_on_select.json
- logs/Mystore/select-on_select-init-on_init-confirm-on_confirm-cancel-on_cancel--f173cb48-b6e5-4dc1-a8b8-4637e5068be7/f173cb48-b6e5-4dc1-a8b8-4637e5068be7_select.json
We have added the logs. 
Also added a Readme file in each mystore log directory in which the url is shared where the whole request/ response can be found.
> Mystore.in logs added

- logs/csc/csc buyer with csc seller/cancel.json
- logs/csc/csc buyer with csc seller/confirm.json
- logs/csc/csc buyer with csc seller/init.json
- logs/csc/csc buyer with csc seller/on_cancel.json
- logs/csc/csc buyer with csc seller/on_confirm.json
- logs/csc/csc buyer with csc seller/on_init.json
- logs/csc/csc buyer with csc seller/on_search.json
- logs/csc/csc buyer with csc seller/on_select.json
- logs/csc/csc buyer with csc seller/on_support.json
- logs/csc/csc buyer with csc seller/search.json
- logs/csc/csc buyer with csc seller/select.json
- logs/csc/csc buyer with csc seller/support.json
- logs/csc/csc seller with ref buyer/cancel.json
- logs/csc/csc seller with ref buyer/confirm.json
- logs/csc/csc seller with ref buyer/init.json
- logs/csc/csc seller with ref buyer/on_cancel.json
- logs/csc/csc seller with ref buyer/on_confirm.json
- logs/csc/csc seller with ref buyer/on_init.json
- logs/csc/csc seller with ref buyer/on_search.json
- logs/csc/csc seller with ref buyer/on_select.json
- logs/csc/csc seller with ref buyer/on_status.json
- logs/csc/csc seller with ref buyer/on_track.json
- logs/csc/csc seller with ref buyer/search.json
- logs/csc/csc seller with ref buyer/select.json
- logs/csc/csc seller with ref buyer/status.json
- logs/csc/csc seller with ref buyer/track.json
Added logs for both csc buyer and seller,  buyer with csc seller & csc seller with preprod ref buyer web app.
> csc transactional logs 

- logs/innobits-enstore/logistics_buyer/init.txt
- logs/innobits-enstore/logistics_buyer/on_search.txt
- logs/innobits-enstore/logistics_buyer/search.txt
- logs/innobits-enstore/retail_seller/cancel.txt
- logs/innobits-enstore/retail_seller/init.txt
- logs/innobits-enstore/retail_seller/on_cancel.txt
- logs/innobits-enstore/retail_seller/on_init.txt
- logs/innobits-enstore/retail_seller/on_select.txt
- logs/innobits-enstore/retail_seller/on_update.txt
- logs/innobits-enstore/retail_seller/select.txt
> Innobits enstore

- logs/innobits-enstore/logistics_buyer/init.txt
- logs/innobits-enstore/logistics_buyer/on_init.txt
- logs/innobits-enstore/retail_seller/cancel.txt
- logs/innobits-enstore/retail_seller/confirm.txt
- logs/innobits-enstore/retail_seller/init.txt
- logs/innobits-enstore/retail_seller/on_cancel.txt
- logs/innobits-enstore/retail_seller/on_confirm.txt
- logs/innobits-enstore/retail_seller/on_init.txt
- logs/innobits-enstore/retail_seller/on_search.txt
- logs/innobits-enstore/retail_seller/search.txt
All changes done! [Issue #81 ](https://github.com/ONDC-Official/Pre-production/issues/81 )
Changed files!
> final changes

- logs/uengage/kotak/cancel.json
- logs/uengage/kotak/confirm.json
- logs/uengage/kotak/init.json
- logs/uengage/kotak/on_cancel.json
- logs/uengage/kotak/on_confirm.json
- logs/uengage/kotak/on_init.json
- logs/uengage/kotak/on_search.json
- logs/uengage/kotak/on_select.json
- logs/uengage/kotak/on_status.json
- logs/uengage/kotak/search.json
- logs/uengage/kotak/select.json
- logs/uengage/mystore/cancel_with_diff_order_id.json
- logs/uengage/mystore/confirm.json
- logs/uengage/mystore/init.json
- logs/uengage/mystore/on_cancel__with_diff_order_id.json
- logs/uengage/mystore/on_confirm.json
- logs/uengage/mystore/on_init.json
- logs/uengage/mystore/on_search.json
- logs/uengage/mystore/on_select.json
- logs/uengage/mystore/on_status.json
- logs/uengage/mystore/search.json
- logs/uengage/mystore/select.json
Cancel flow in mystore buyer app is tested with different  order id as last order's status was marked shipped so it could not be cancelled from the buyer app.
> Uengage: updated logs with kotak and mytore

- logs/innobits-enstore/mystore/logistics_bap/l_cancel.txt
- logs/innobits-enstore/mystore/logistics_bap/l_confirm.txt
- logs/innobits-enstore/mystore/logistics_bap/l_init.txt
- logs/innobits-enstore/mystore/logistics_bap/l_on_update.txt
- logs/innobits-enstore/mystore/logistics_bap/l_search.txt
- logs/innobits-enstore/mystore/logistics_bap/l_status.txt
- logs/innobits-enstore/mystore/logistics_bap/l_track.txt
- logs/innobits-enstore/mystore/retail_seller/cancel.txt
- logs/innobits-enstore/mystore/retail_seller/confirm.txt
- logs/innobits-enstore/mystore/retail_seller/init.txt
- logs/innobits-enstore/mystore/retail_seller/on_update.txt
- logs/innobits-enstore/mystore/retail_seller/search.txt
- logs/innobits-enstore/mystore/retail_seller/select.txt
- logs/innobits-enstore/mystore/retail_seller/status.txt
- logs/innobits-enstore/mystore/retail_seller/track.txt
@BLR-0118  update logs as per the review, please look into the mystore folder
@dashbitla-ib
> Mystore logs

- logs/innobits-enstore/mystore_updated/retail_seller/init.txt
- logs/innobits-enstore/mystore_updated/retail_seller/on_update.txt
- logs/innobits-enstore/mystore_updated/retail_seller/search.txt
@BLR-0118 added changes as per the review, please check mystore_updated folder
@dashbitla-ib
> review changes

- logs/innobits-enstore/mystore_updated_v2/init.txt
@BLR-0118 linking item_id and fulfillment_id in order - on_init
@dashbitla-ib
> fulfillments ids and item ids relation

- logs/nstore/nStore_Logistics_BAP.log
- logs/nstore/nStore_Retail_BPP.log
nStore Retail BPP - status, on_status, update, on_update API added
nStore Logistics BAP - support, on_support API added
updated on 12/09/2022
> nStore Retail BPP and nStore Logistics BAP missed logs updated on 12/09/2022

- logs/csc/csc seller with mystore buyer/confirm.json
- logs/csc/csc seller with mystore buyer/init.json
- logs/csc/csc seller with mystore buyer/on_confirm.json
- logs/csc/csc seller with mystore buyer/on_init.json
- logs/csc/csc seller with mystore buyer/on_search.json
- logs/csc/csc seller with mystore buyer/on_select.json
- logs/csc/csc seller with mystore buyer/on_status.json
- logs/csc/csc seller with mystore buyer/on_track.json
- logs/csc/csc seller with mystore buyer/search.json
- logs/csc/csc seller with mystore buyer/select.json
- logs/csc/csc seller with mystore buyer/status.json
- logs/csc/csc seller with mystore buyer/track.json
Transaction logs between CSC Seller and Mystore Buyer.
Note: Could not find any way to initial /support call from buyer. Also,  no /cancel or /update as  seller cancellable and returnable is false.
> csc seller logs with beta.mystore.in buyer

- logs/Mystore/Mystore buyer app/Testing with enstore seller app/088f98b2-7e57-48b7-9787-c3299f50df31_on_search.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/088f98b2-7e57-48b7-9787-c3299f50df31_search.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/Readme
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_cancel.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_confirm.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_init.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_cancel.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_confirm.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_init.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_select.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_status.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_support.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_on_track.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_select.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_status.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_support.json
- logs/Mystore/Mystore buyer app/Testing with enstore seller app/d319101e-da21-485d-9acc-21065be2e0e5_track.json
Adding Mystore buyer app logs with testing to enstore seller app
> Adding Mystore buyer app logs with testing to enstore seller app

- logs/nstore/nStore_Retail_BPP.log
Retail BPP logs updated - 16/09/2022
> Retail BPP logs updated - 16/09/2022

- logs/nstore/nStore_Retail_BPP.log
[nStore Retail BPP latest log updated on 21/09/22](https://github.com/ONDC-Official/Pre-production/commit/3d2090dfd7601a88ff039666950f13a273d3533c)
> nStore Retail BPP latest log updated on 21/09/22

- logs/nstore/nStore_Retail_BPP.log
[nStore Retail BPP logs updated on 22/09/22](https://github.com/ONDC-Official/Pre-production/commit/1b8c65075486a1098beeae4a395def5e91e16439)
> nStore Retail BPP logs updated on 22/09/22

- logs/NiveaShop/KotakLogs/confirm.json
- logs/NiveaShop/KotakLogs/init.json
- logs/NiveaShop/KotakLogs/on_confirm.json
- logs/NiveaShop/KotakLogs/on_init.json
- logs/NiveaShop/KotakLogs/on_search.json
- logs/NiveaShop/KotakLogs/on_select.json
- logs/NiveaShop/KotakLogs/on_status.json
- logs/NiveaShop/KotakLogs/search.json
- logs/NiveaShop/KotakLogs/select.json
- logs/NiveaShop/KotakLogs/status.json
- logs/NiveaShop/MyStoreLogs/confirm.json
- logs/NiveaShop/MyStoreLogs/init.json
- logs/NiveaShop/MyStoreLogs/on_confirm.json
- logs/NiveaShop/MyStoreLogs/on_init.json
- logs/NiveaShop/MyStoreLogs/on_search.json
- logs/NiveaShop/MyStoreLogs/on_select.json
- logs/NiveaShop/MyStoreLogs/on_status.json
- logs/NiveaShop/MyStoreLogs/search.json
- logs/NiveaShop/MyStoreLogs/select.json
- logs/NiveaShop/MyStoreLogs/status.json
Added logs from search to status along with the callbacks and callback responses. 
logs/NiveaShop/MyStoreLogs - All the logs generated while testing with MyStore Pre prod Buyer App
logs/NiveaShop/KotakLogs - All the logs generated while testing with Kotak Pre prod Buyer App.
> Nivea Shop Preprod Logs - MyStore and Kotak

- logs/zoho/loadshare/logs-26-09-22/confirm.json
- logs/zoho/loadshare/logs-26-09-22/init.json
- logs/zoho/loadshare/logs-26-09-22/search.json
- logs/zoho/loadshare/logs-26-09-22/status.json
- logs/zoho/mystore/logs-26-09-22/on_confirm.json
- logs/zoho/mystore/logs-26-09-22/on_init.json
- logs/zoho/mystore/logs-26-09-22/on_search.json
- logs/zoho/mystore/logs-26-09-22/on_select.json
- logs/zoho/mystore/logs-26-09-22/on_status.json
- logs/zoho/spiceonline/logs-26-09-22/on_search.json
Zoho Seller App Logs with mystore buyer app and loadshare logistics.
> Zoho Seller App Logs

- logs/zoho/loadshare/logs-26-09-22/confirm.json
- logs/zoho/loadshare/logs-26-09-22/init.json
- logs/zoho/loadshare/logs-26-09-22/search.json
- logs/zoho/loadshare/logs-26-09-22/status.json
- logs/zoho/mystore/logs-26-09-22/on_confirm.json
- logs/zoho/mystore/logs-26-09-22/on_init.json
- logs/zoho/mystore/logs-26-09-22/on_search.json
- logs/zoho/mystore/logs-26-09-22/on_select.json
- logs/zoho/mystore/logs-26-09-22/on_status.json
- logs/zoho/spiceonline/logs-26-09-22/on_search.json
Include Other Apps request in logs.
> Update Logs 

- logs/NiveaShop/KotakLogs/confirm.json
- logs/NiveaShop/KotakLogs/init.json
- logs/NiveaShop/KotakLogs/on_confirm.json
- logs/NiveaShop/KotakLogs/on_init.json
- logs/NiveaShop/KotakLogs/on_select.json
- logs/NiveaShop/KotakLogs/on_status.json
- logs/NiveaShop/KotakLogs/on_support.json
- logs/NiveaShop/KotakLogs/select.json
- logs/NiveaShop/KotakLogs/support.json
- logs/NiveaShop/MyStoreLogs/confirm.json
- logs/NiveaShop/MyStoreLogs/init.json
- logs/NiveaShop/MyStoreLogs/on_confirm.json
- logs/NiveaShop/MyStoreLogs/on_init.json
- logs/NiveaShop/MyStoreLogs/on_select.json
- logs/NiveaShop/MyStoreLogs/on_status.json
- logs/NiveaShop/MyStoreLogs/select.json
- logs/NiveaShop/MyStoreLogs/status.json
For MyStore the /support calls aren't being recieved. Added /support and /on_support requests with Kotak buyer app.
Nivea does not support any type of cancellation of orders once order is placed, hence no order cancellation logs.
> NIVEASHOP - compliance issues #233

- logs/zoho/buyer-app-preprod/27-09-22/cancel.json
- logs/zoho/buyer-app-preprod/27-09-22/confirm.json
- logs/zoho/buyer-app-preprod/27-09-22/init.json
- logs/zoho/buyer-app-preprod/27-09-22/search.json
- logs/zoho/buyer-app-preprod/27-09-22/select.json
- logs/zoho/buyer-app-preprod/27-09-22/status.json
- logs/zoho/buyer-app-preprod/27-09-22/support.json
- logs/zoho/buyer-app-preprod/27-09-22/track.json
- logs/zoho/buyer-app-preprod/27-09-22/update.json
> pre-prod buyer app logs

- logs/grab/logs_2022-10-15/unsolicited_oncancel.txt
Grab - Nstore test logs for unsolicited /on_cancel - 2022-10-15
> Grab - Nstore test logs for unsolicited /on_cancel

- logs/NiveaShop/MyStoreLogs/confirm.json
- logs/NiveaShop/MyStoreLogs/init.json
- logs/NiveaShop/MyStoreLogs/on_confirm.json
- logs/NiveaShop/MyStoreLogs/on_init.json
- logs/NiveaShop/MyStoreLogs/on_search.json
- logs/NiveaShop/MyStoreLogs/on_select.json
- logs/NiveaShop/MyStoreLogs/on_status.json
- logs/NiveaShop/MyStoreLogs/on_support.json
- logs/NiveaShop/MyStoreLogs/on_track.json
- logs/NiveaShop/MyStoreLogs/search.json
- logs/NiveaShop/MyStoreLogs/select.json
- logs/NiveaShop/MyStoreLogs/status.json
- logs/NiveaShop/MyStoreLogs/track.json
Hi Supriyo,
Added the /support call response. Updated /status in accordance with API contract. Kindly review.
Regards,
Agam
> Logs uploaded after end to end testing with MyStore

- signing_and_verification/README.md
- signing_and_verification/cryptic_utils.py
Verify using request.data i.e. request raw payload string instead of minified version of request json
> Update verify-header function: use request.data string instead of json

- logs/magicpin/Logs with mystore/CancelRequest.txt
- logs/magicpin/Logs with mystore/ConfirmRequest.txt
- logs/magicpin/Logs with mystore/InitRequest.txt
- logs/magicpin/Logs with mystore/SearchRequest.txt
- logs/magicpin/Logs with mystore/SelectRequest.txt
- logs/magicpin/Logs with mystore/StatusRequest.txt
- logs/magicpin/Logs with mystore/TrackRequest.txt
1. /update api is not available from mystore buyer app as the items are non returnable and non cancellable
2. mystore /support api is not working
3. At the time of order creation the state is set as "created", once the merchant accepts the order it will be updated to "accepted"
> added new logs with mystore

- logs/thesellerapp/thesellerapp<>meesho_logs/cancel.json
- logs/thesellerapp/thesellerapp<>meesho_logs/confirm.json
- logs/thesellerapp/thesellerapp<>meesho_logs/init.json
- logs/thesellerapp/thesellerapp<>meesho_logs/search.json
- logs/thesellerapp/thesellerapp<>meesho_logs/select.json
- logs/thesellerapp/thesellerapp<>meesho_logs/status.json
- logs/thesellerapp/thesellerapp<>meesho_logs/support.json
- logs/thesellerapp/thesellerapp<>meesho_logs/track.json
- logs/thesellerapp/thesellerapp<>meesho_logs/update.json
thesellerapp<>meesho log added
> thesellerapp<>meesho log added

- logs/Gogappi/Sellerapp/confirm.json
- logs/Gogappi/Sellerapp/init.json
- logs/Gogappi/Sellerapp/on_cancel.json
- logs/Gogappi/Sellerapp/on_confirm.json
- logs/Gogappi/Sellerapp/on_init.json
- logs/Gogappi/Sellerapp/on_search.json
- logs/Gogappi/Sellerapp/on_select.json
- logs/Gogappi/Sellerapp/on_status.json
- logs/Gogappi/Sellerapp/on_support.json
- logs/Gogappi/Sellerapp/search.json
- logs/Gogappi/Sellerapp/select.json
- logs/Gogappi/Sellerapp/status.json
- logs/Gogappi/Sellerapp/support.json
- logs/Gogappi/Uengage/confirm.json
- logs/Gogappi/Uengage/init.json
- logs/Gogappi/Uengage/on_confirm.json
- logs/Gogappi/Uengage/on_init.json
- logs/Gogappi/Uengage/on_search.json
- logs/Gogappi/Uengage/on_select.json
- logs/Gogappi/Uengage/on_status.json
- logs/Gogappi/Uengage/on_support.json
- logs/Gogappi/Uengage/search.json
- logs/Gogappi/Uengage/select.json
- logs/Gogappi/Uengage/status.json
- logs/Gogappi/Uengage/support.json
Made changes, solved a couple of minor issues.
> Gogappi - Resubmitting modified logs

- logs/theushop/init_1.json
- logs/theushop/status_1.json
> logs-updated

- logs/VLCC/cancle.json
- logs/VLCC/confirmlog.json
- logs/VLCC/initlog.json
- logs/VLCC/searchlog.json
- logs/VLCC/selectlog.json
- logs/VLCC/statuslog.json
- logs/VLCC/supportlog.json
- logs/VLCC/track.json
- logs/VLCC/update.json
some file changes and added cancle, update, support, track file.
> commit no 2 some file changes and added

- logs/VLCC/cancle.json
- logs/VLCC/confirmlog.json
- logs/VLCC/initlog.json
- logs/VLCC/searchlog.json
- logs/VLCC/selectlog.json
- logs/VLCC/statuslog.json
- logs/VLCC/supportlog.json
- logs/VLCC/track.json
- logs/VLCC/update.json
some changes and new updated logs
> commit no 3

- logs/theushop/status_4.json
> status logs update

- logs/Addble/Mystore_Addble_Blowhorn/Logistic/confirm.json
- logs/Addble/Mystore_Addble_Blowhorn/Logistic/init.json
- logs/Addble/Mystore_Addble_Blowhorn/Logistic/search.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/confirm.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/init.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/on_confirm.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/on_init.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/on_search.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/on_select.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/select.json
Updated logs with fixes for comments in issue #343
> Addble compliance logs with fixes for issue #343

- logs/VLCC/cancle.json
- logs/VLCC/confirmlog.json
- logs/VLCC/initlog.json
- logs/VLCC/searchlog.json
- logs/VLCC/selectlog.json
- logs/VLCC/statuslog.json
- logs/VLCC/supportlog.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> all bug fix

- logs/signcatch/signcatch_mystore(seller app)/cancel.json
- logs/signcatch/signcatch_mystore(seller app)/confirm.json
- logs/signcatch/signcatch_mystore(seller app)/init.json
- logs/signcatch/signcatch_mystore(seller app)/on_cancel.json
- logs/signcatch/signcatch_mystore(seller app)/on_init.json
- logs/signcatch/signcatch_mystore(seller app)/on_search.json
- logs/signcatch/signcatch_mystore(seller app)/on_select.json
- logs/signcatch/signcatch_mystore(seller app)/on_status_PostCancel.json
- logs/signcatch/signcatch_mystore(seller app)/on_status_PreCancel.json
- logs/signcatch/signcatch_mystore(seller app)/search.json
- logs/signcatch/signcatch_mystore(seller app)/select.json
- logs/signcatch/signcatch_mystore(seller app)/status.json
- logs/signcatch/signcatch_mystore(seller app)/track.json
updated logs with request and response json for compliance check. Currently we are not supporting the partial cancellation or return so update api json isn't included.
> signcatch seller app updated logs with mystore

- logs/Addble/Mystore_Addble_Blowhorn/Retail/on_select.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/on_track.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/select.json
- logs/Addble/Mystore_Addble_Blowhorn/Retail/track.json
- logs/Addble/Plotch-Indiastack_Addble/confirm.json
- logs/Addble/Plotch-Indiastack_Addble/init.json
- logs/Addble/Plotch-Indiastack_Addble/on_confirm.json
- logs/Addble/Plotch-Indiastack_Addble/on_init.json
- logs/Addble/Plotch-Indiastack_Addble/on_search.json
- logs/Addble/Plotch-Indiastack_Addble/on_select.json
- logs/Addble/Plotch-Indiastack_Addble/on_status.json
- logs/Addble/Plotch-Indiastack_Addble/on_support.json
- logs/Addble/Plotch-Indiastack_Addble/on_track.json
- logs/Addble/Plotch-Indiastack_Addble/on_update.json
- logs/Addble/Plotch-Indiastack_Addble/search.json
- logs/Addble/Plotch-Indiastack_Addble/select.json
- logs/Addble/Plotch-Indiastack_Addble/support.json
- logs/Addble/Plotch-Indiastack_Addble/track.json
- logs/Addble/Plotch-Indiastack_Addble/update.json
Added fix for https://github.com/ONDC-Official/verification-logs/issues/343#issuecomment-1336478101
- Moved delivery charge to on_select
- /on_support
- /on_track
- /on_update via testing with Plotch_Indiastack
> Added fixes for issue #343 - Addble

- logs/Snapdeal_mystoreLogs/dec-15-2022/on_search.json
- logs/Snapdeal_mystoreLogs/dec-15-2022/on_select.json
- logs/Snapdeal_mystoreLogs/dec-15-2022/search.json
- logs/Snapdeal_mystoreLogs/dec-15-2022/select.json
We are able to test and collect the latest logs for search and select apis using mystore. Mystore has an issue of saying product is not serviceable even though we are sending serviceable. We could not proceed further with testing
> latest search and select logs

- logs/thesellerapp/thesellerapp<>meesho_logs/cancel.json
- logs/thesellerapp/thesellerapp<>meesho_logs/confirm.json
- logs/thesellerapp/thesellerapp<>meesho_logs/init.json
- logs/thesellerapp/thesellerapp<>meesho_logs/search.json
- logs/thesellerapp/thesellerapp<>meesho_logs/select.json
- logs/thesellerapp/thesellerapp<>meesho_logs/status.json
- logs/thesellerapp/thesellerapp<>meesho_logs/support.json
- logs/thesellerapp/thesellerapp<>meesho_logs/track.json
- logs/thesellerapp/thesellerapp<>meesho_logs/update.json
> end to end logs

- logs/protean-rsp/COLLECTOR_RECON.json
- logs/protean-rsp/ONCOLLECTOR_RECON.json
- logs/protean-rsp/ONRECEIVER_RECON.json
- logs/protean-rsp/ON_SETTLE.json
- logs/protean-rsp/RECEIVER_RECON.json
- logs/protean-rsp/SETTLE.json
Uploading logs for RSP flow for verification
> Protean RSP logs

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> commit no14

- logs/thesellerapp/thesellerapp<>meesho_logs/cancel.json
- logs/thesellerapp/thesellerapp<>meesho_logs/confirm.json
- logs/thesellerapp/thesellerapp<>meesho_logs/init.json
- logs/thesellerapp/thesellerapp<>meesho_logs/search.json
- logs/thesellerapp/thesellerapp<>meesho_logs/select.json
- logs/thesellerapp/thesellerapp<>meesho_logs/status.json
- logs/thesellerapp/thesellerapp<>meesho_logs/support.json
- logs/thesellerapp/thesellerapp<>meesho_logs/track.json
- logs/thesellerapp/thesellerapp<>meesho_logs/update.json
> all issue resolve

- logs/Addble/Plotch-Indiastack_Addble/confirm.json
- logs/Addble/Plotch-Indiastack_Addble/init.json
- logs/Addble/Plotch-Indiastack_Addble/on_confirm.json
- logs/Addble/Plotch-Indiastack_Addble/on_init.json
- logs/Addble/Plotch-Indiastack_Addble/on_search.json
- logs/Addble/Plotch-Indiastack_Addble/on_select.json
- logs/Addble/Plotch-Indiastack_Addble/on_update.json
- logs/Addble/Plotch-Indiastack_Addble/search.json
- logs/Addble/Plotch-Indiastack_Addble/select.json
- logs/Addble/Plotch-Indiastack_Addble/update.json
1. Added new serviceability construct in /on_search 
2. Fixed quote.price.value not matching with breakup price due to precision issue in /on_select and /on_update
> Addble compliance check fixes

- logs/Addble/Plotch-Indiastack_Addble/on_search.json
- logs/Addble/Plotch-Indiastack_Addble/search.json
Incorporated updated serviceability construct in on_search
@BLR-0118
> Addble compliance check - updated with latest serviceability construct

- logs/Nearshop/cancel.json
- logs/Nearshop/confirm.json
- logs/Nearshop/init.json
- logs/Nearshop/on_cancel.json
- logs/Nearshop/on_confirm_for_validation_update.json
- logs/Nearshop/on_init.json
- logs/Nearshop/on_search.json
- logs/Nearshop/on_select.json
- logs/Nearshop/on_status.json
- logs/Nearshop/on_support.json
- logs/Nearshop/on_track.json
- logs/Nearshop/on_update.json
- logs/Nearshop/search.json
- logs/Nearshop/select.json
- logs/Nearshop/status.json
- logs/Nearshop/support.json
- logs/Nearshop/track.json
- logs/Nearshop/update.json
1) /on_search:
item.exp is invalid key;
what does this fulfillment id mean? ("fulfillment_id": "44f1a436-8eb8-5bb7-93e7-39e2324efcb7")
**Fixed**
2)/on_select:
item price shown in /on_search is broken into item & tax line items. This is not allowed as for this category, the item price shown in catalog is already tax inclusive;
**Fixed**
3)/on_init:
several invalid keys in payment struct;
**Fixed**
4)/on_confirm:
no default fulfillment state;
**Fixed**
5)/on_cancel:
order.state is duplicated;
**Fixed**
6)/on_status: no fulfillment state;
**Fixed**
7)/update & /on_update are using different order id making it difficult to verify.
**Fixed**
> Nearshop Logs(Review, Comments & Fixes)

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> all issue fix commit no 15

- logs/Addble/Plotch-Indiastack_Addble/on_search.json
- logs/Addble/Plotch-Indiastack_Addble/search.json
Updated serviceability category as per latest serviceability spec in on_search
@BLR-0118  - please review
> Addble compliance logs - serviceability update

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> issue fix commit no 17

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> init confirm and update fix issue

- logs/Anek/Groupbuy_logs/GroupBuyOrder_ConfirmRequest.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_ConfirmResponse.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_InitRequest.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_InitResponse.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_SearchRequest.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_SearchResponse.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_SelectRequest.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_SelectResponse.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_StatusRequest.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_StatusResponse.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_SupportRequest.json
- logs/Anek/Groupbuy_logs/GroupBuyOrder_SupportResponse.json
Groupbuy logs for Anek with Esamudaay seller app.
> Groupbuy logs for Anek with Esamudaay seller app.

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/on_cancel.json
- logs/VLCC/on_confirm.json
- logs/VLCC/on_init.json
- logs/VLCC/on_search.json
- logs/VLCC/on_select.json
- logs/VLCC/on_status.json
- logs/VLCC/on_support.json
- logs/VLCC/on_track.json
- logs/VLCC/on_update.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> commit no 20 all issue fix

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/on_cancel.json
- logs/VLCC/on_confirm.json
- logs/VLCC/on_init.json
- logs/VLCC/on_search.json
- logs/VLCC/on_select.json
- logs/VLCC/on_status.json
- logs/VLCC/on_support.json
- logs/VLCC/on_track.json
- logs/VLCC/on_update.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
select,init,status issue fix commit no 21
> select,init,status issue fix commit no 21

- logs/VLCC/on_update.json
> on_update api

- logs/Nearshop/cancel.json
- logs/Nearshop/confirm.json
- logs/Nearshop/init.json
- logs/Nearshop/on_cancel.json
- logs/Nearshop/on_confirm.json
- logs/Nearshop/on_init.json
- logs/Nearshop/on_search.json
- logs/Nearshop/on_select.json
- logs/Nearshop/on_status.json
- logs/Nearshop/on_support.json
- logs/Nearshop/on_track.json
- logs/Nearshop/on_update.json
- logs/Nearshop/payload_for_cancel.json
- logs/Nearshop/search.json
- logs/Nearshop/select.json
- logs/Nearshop/status.json
- logs/Nearshop/support.json
- logs/Nearshop/track.json
- logs/Nearshop/update.json
**FIXED:**
/on_select
items.quantity.selected is invalid key.
quote.breakup price value should be of individual count.
/on_confirm
order timestamp is updated when there is a change in order state.
/on_update
tags.status should be "Cancelled"
For on_cancel a separate order is created (payload_for_cancel file has its on_confirm payload.) as india stack buyer app invokes update api call again.
> Nearshop Verification Logs (Review, Comments, & Fixes)

- logs/VLCC/cancel.json
- logs/VLCC/confirm.json
- logs/VLCC/init.json
- logs/VLCC/on_cancel.json
- logs/VLCC/on_confirm.json
- logs/VLCC/on_init.json
- logs/VLCC/on_search.json
- logs/VLCC/on_select.json
- logs/VLCC/on_status.json
- logs/VLCC/on_support.json
- logs/VLCC/on_track.json
- logs/VLCC/on_update.json
- logs/VLCC/search.json
- logs/VLCC/select.json
- logs/VLCC/status.json
- logs/VLCC/support.json
- logs/VLCC/track.json
- logs/VLCC/update.json
> select update and status issue fix

- logs/Shipyaari/Shipyaari-Eunimarts/cancel.json
- logs/Shipyaari/Shipyaari-Eunimarts/confirm.json
- logs/Shipyaari/Shipyaari-Eunimarts/init.json
- logs/Shipyaari/Shipyaari-Eunimarts/on_cancel.json
- logs/Shipyaari/Shipyaari-Eunimarts/on_confirm.json
- logs/Shipyaari/Shipyaari-Eunimarts/on_init.json
- logs/Shipyaari/Shipyaari-Eunimarts/on_search.json
- logs/Shipyaari/Shipyaari-Eunimarts/on_status.json
- logs/Shipyaari/Shipyaari-Eunimarts/on_track.json
- logs/Shipyaari/Shipyaari-Eunimarts/search.json
- logs/Shipyaari/Shipyaari-Eunimarts/status.json
- logs/Shipyaari/Shipyaari-Eunimarts/track.json
Logs Added for 
search, init, confirm, track, status, cancel, on_search, on_init, on_confirm, on_track, on_status, on_cancel
> First Commit: Added logs

- logs/ndhgo/reference-app-logs/flow5/cancel.json
- logs/ndhgo/reference-app-logs/flow5/confirm.json
- logs/ndhgo/reference-app-logs/flow5/init.json
- logs/ndhgo/reference-app-logs/flow5/on_cancel.json
- logs/ndhgo/reference-app-logs/flow5/on_confirm.json
- logs/ndhgo/reference-app-logs/flow5/on_init.json
- logs/ndhgo/reference-app-logs/flow5/on_search.json
- logs/ndhgo/reference-app-logs/flow5/on_select.json
- logs/ndhgo/reference-app-logs/flow5/on_status-before.json
- logs/ndhgo/reference-app-logs/flow5/search.json
- logs/ndhgo/reference-app-logs/flow5/select.json
- logs/ndhgo/reference-app-logs/flow5/status-before.json
> Flow5 Logs - NDHGO Fix

- logs/ndhgo/reference-app-logs/flow4/confirm.json
- logs/ndhgo/reference-app-logs/flow4/init.json
- logs/ndhgo/reference-app-logs/flow4/on_confirm.json
- logs/ndhgo/reference-app-logs/flow4/on_init.json
- logs/ndhgo/reference-app-logs/flow4/on_search.json
- logs/ndhgo/reference-app-logs/flow4/on_select.json
- logs/ndhgo/reference-app-logs/flow4/on_status-after.json
- logs/ndhgo/reference-app-logs/flow4/on_status-before.json
- logs/ndhgo/reference-app-logs/flow4/on_update.json
- logs/ndhgo/reference-app-logs/flow4/search.json
- logs/ndhgo/reference-app-logs/flow4/select.json
- logs/ndhgo/reference-app-logs/flow4/status-after.json
- logs/ndhgo/reference-app-logs/flow4/status-before.json
- logs/ndhgo/reference-app-logs/flow4/unsolicited_status.json
- logs/ndhgo/reference-app-logs/flow4/update.json
Issue Related: #444 
Comment Addressed: [Linked here](https://github.com/ONDC-Official/verification-logs/issues/444#issuecomment-1448715719)
> NDHGO - Feb 26 Logs Issue Fixes

- logs/NBBL/RSP/collector_recon.json
- logs/NBBL/RSP/on_collector_recon.json
- logs/NBBL/RSP/on_receiver_recon.json
- logs/NBBL/RSP/on_recon_status.json
- logs/NBBL/RSP/receiver_recon.json
- logs/NBBL/RSP/recon_status.json
- logs/NBBL/SA/on_settle.json
- logs/NBBL/SA/settle.json
When NBBL as RSP - /collector_recon , /on_collector_recon , /receiver_recon , /on_receiver_recon , /recon_status and /on_recon_status api's
When NBBL as an SA for External RSP - /settle and /on_settle api's
> Logs for NBBL as an RSP and SA(For External RSP)

- logs/JioMart/BuyerApp/Flow1/confirm.json
- logs/JioMart/BuyerApp/Flow1/init.json
- logs/JioMart/BuyerApp/Flow1/on_confirm.json
- logs/JioMart/BuyerApp/Flow1/on_init.json
- logs/JioMart/BuyerApp/Flow1/on_search.json
- logs/JioMart/BuyerApp/Flow1/on_select.json
- logs/JioMart/BuyerApp/Flow1/on_status.json
- logs/JioMart/BuyerApp/Flow1/on_status_after_update.json
- logs/JioMart/BuyerApp/Flow1/on_update.json
- logs/JioMart/BuyerApp/Flow1/search.json
- logs/JioMart/BuyerApp/Flow1/select.json
- logs/JioMart/BuyerApp/Flow1/status.json
- logs/JioMart/BuyerApp/Flow1/status_after_update.json
- logs/JioMart/BuyerApp/Flow1/update.json
> Jiomart: fix flow 1

- logs/Magicpin-logistics/cancel.json
- logs/Magicpin-logistics/confirm.json
- logs/Magicpin-logistics/init.json
- logs/Magicpin-logistics/on_cancel.json
- logs/Magicpin-logistics/on_confirm.json
- logs/Magicpin-logistics/on_init.json
- logs/Magicpin-logistics/on_search.json
- logs/Magicpin-logistics/on_status.json
- logs/Magicpin-logistics/on_status_assigned.json
- logs/Magicpin-logistics/on_status_delivered.json
- logs/Magicpin-logistics/on_status_out_for_delivery.json
- logs/Magicpin-logistics/on_support.json
- logs/Magicpin-logistics/search.json
- logs/Magicpin-logistics/status.json
- logs/Magicpin-logistics/support.json
> Magicpin as a logistics provider

- logs/Rapidor/rapidor_own_seller_app/cancel.json
- logs/Rapidor/rapidor_own_seller_app/confirm.json
- logs/Rapidor/rapidor_own_seller_app/init.json
- logs/Rapidor/rapidor_own_seller_app/on_cancel.json
- logs/Rapidor/rapidor_own_seller_app/on_confirm.json
- logs/Rapidor/rapidor_own_seller_app/on_init.json
- logs/Rapidor/rapidor_own_seller_app/on_search.json
- logs/Rapidor/rapidor_own_seller_app/on_select.json
- logs/Rapidor/rapidor_own_seller_app/on_status(Post Cancel).json
- logs/Rapidor/rapidor_own_seller_app/on_status.json
- logs/Rapidor/rapidor_own_seller_app/search.json
- logs/Rapidor/rapidor_own_seller_app/select.json
- logs/Rapidor/rapidor_own_seller_app/status.json
> feat: Add Changes Based on #594

- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_D.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_OFD.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_OPU.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_SFA.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/confirm.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/init.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/on_confirm.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/on_init.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/on_search.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/on_track.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/on_update.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/search.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/track.json
- logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/update.json
@BLR-0118 
I have updated the Test Scenario 1 as per your comments over [here](https://github.com/ONDC-Official/v1.1.0-logs/issues/105#issuecomment-1510372299)
Kindly review
> Updated Test Scenario1 as per review with Viranc Infotech

- logs/razorpay-rsp/collector_recon.json
- logs/razorpay-rsp/on_collector_recon.json
- logs/razorpay-rsp/on_receiver_recon.json
- logs/razorpay-rsp/on_recon_status.json
- logs/razorpay-rsp/on_settle.json
- logs/razorpay-rsp/receiver_recon.json
- logs/razorpay-rsp/recon_status.json
> Fix logs based on comments on 16-04-2023 issue #606

- logs/ChaiPoint/Flow 1/confirm.json
- logs/ChaiPoint/Flow 1/init.json
- logs/ChaiPoint/Flow 1/on_confirm.json
- logs/ChaiPoint/Flow 1/on_init.json
- logs/ChaiPoint/Flow 1/on_search.json
- logs/ChaiPoint/Flow 1/on_select.json
- logs/ChaiPoint/Flow 1/on_status.json
- logs/ChaiPoint/Flow 1/search.json
- logs/ChaiPoint/Flow 1/select.json
- logs/ChaiPoint/Flow 2/confirm.json
- logs/ChaiPoint/Flow 2/init.json
- logs/ChaiPoint/Flow 2/on_cancel.json
- logs/ChaiPoint/Flow 2/on_confirm.json
- logs/ChaiPoint/Flow 2/on_init.json
- logs/ChaiPoint/Flow 2/on_search.json
- logs/ChaiPoint/Flow 2/on_select.json
- logs/ChaiPoint/Flow 2/search.json
- logs/ChaiPoint/Flow 2/select.json
@BLR-0118 Please merge our PR to main branch
@bluecypher Please validate our logs, we've run the script and found no error in our logs. If issue persists further then please connect with us regarding this.
> Chai point

- logs/Delcaper/Addble/Logistics-Test-Scenario-1/confirm.json
- logs/Delcaper/Addble/Logistics-Test-Scenario-1/init.json
- logs/Delcaper/Addble/Logistics-Test-Scenario-1/on_confirm.json
- logs/Delcaper/Addble/Logistics-Test-Scenario-1/on_init.json
- logs/Delcaper/Addble/Logistics-Test-Scenario-1/on_search.json
- logs/Delcaper/Addble/Logistics-Test-Scenario-1/serach.json
- logs/Delcaper/VirancInfotech/Logistics-Cancel Scenario/cancel.json
- logs/Delcaper/VirancInfotech/Logistics-Cancel Scenario/on_cancel.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_D.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_OFD.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated Status Calls/on_status_OPU.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/confirm.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/init.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_confirm.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_init.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_search.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_status.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_support.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_track.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/on_update.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/serach.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/status.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/support.json
- logs/Delcaper/VirancInfotech/Logistics-Test-Scenario-1/update.json
Updated Logs From Delcaper After compliance check Issue Fixed
> Updated Logs From Delcaper After compliance check Issue Fixed

- logs/Xpressbees/Flow 1/10_On_StatusAfterOrderPickupUp.json
- logs/Xpressbees/Flow 1/11_StatusAfterOutForDelivery.json
- logs/Xpressbees/Flow 1/12_On_StatusAfterOutForDelivery.json
- logs/Xpressbees/Flow 1/13_StatusAfterOrderDelivery.json
- logs/Xpressbees/Flow 1/14_On_StatusAfterOrderDelivery.json
- logs/Xpressbees/Flow 1/1_search.json
- logs/Xpressbees/Flow 1/2_OnSearch.json
- logs/Xpressbees/Flow 1/3_Init.json
- logs/Xpressbees/Flow 1/4_On_Init.json
- logs/Xpressbees/Flow 1/5_Confirm.json
- logs/Xpressbees/Flow 1/6_OnConfirm.json
- logs/Xpressbees/Flow 1/7_StatusAfterOn_Confirm.json
- logs/Xpressbees/Flow 1/8_On_StatusAfterOn_Confirm.json
- logs/Xpressbees/Flow 1/9_StatusAfterOrderPickupUp.json
- logs/Xpressbees/Flow 2/10_On_StatusAfterOrderPickup.json
- logs/Xpressbees/Flow 2/11_OnCancel.json
- logs/Xpressbees/Flow 2/12_StatusAfterCancelFromLogistic.json
- logs/Xpressbees/Flow 2/13_On_StatusAfterCancelFromLogistic.json
- logs/Xpressbees/Flow 2/1_search.json
- logs/Xpressbees/Flow 2/2_OnSearch.json
- logs/Xpressbees/Flow 2/3_Init.json
- logs/Xpressbees/Flow 2/4_OnInit.json
- logs/Xpressbees/Flow 2/5_Confirm.json
- logs/Xpressbees/Flow 2/6_OnConfirm.json
- logs/Xpressbees/Flow 2/7_StatusAfterOnConfirm.json
- logs/Xpressbees/Flow 2/8_On_StatusAfterOnConfirm.json
- logs/Xpressbees/Flow 2/9_StatusAfterOrderPickup.json
**Changes:**
Added logs for Xpressbess (LSP) for forward and rto flow.
> Xpressbees (LSP) v1.1.0 logs for forward and rto flow

- logs/InstaStack/flow_1/01_issue.json
- logs/InstaStack/flow_1/02_on_issue_processing.json
- logs/InstaStack/flow_1/03_issue_status.json
- logs/InstaStack/flow_1/04_on_issue_status_resolved.json
- logs/InstaStack/flow_1/05_issue_closed.json
- logs/InstaStack/flow_2/01_issue.json
- logs/InstaStack/flow_2/02_on_issue_processing.json
- logs/InstaStack/flow_2/03_issue_status.json
- logs/InstaStack/flow_2/04_on_issue_status_resolved.json
- logs/InstaStack/flow_2/05_issue_closed.json
> IGM logs from InstaStack MSN

- TRV10/Yatri Sathi/Normal Flow/confirm.json
- TRV10/Yatri Sathi/Normal Flow/init.json
- TRV10/Yatri Sathi/Normal Flow/on_confirm.json
- TRV10/Yatri Sathi/Normal Flow/on_init.json
- TRV10/Yatri Sathi/Normal Flow/on_search.json
- TRV10/Yatri Sathi/Normal Flow/on_select.json
- TRV10/Yatri Sathi/Normal Flow/on_track.json
- TRV10/Yatri Sathi/Normal Flow/on_update1.json
- TRV10/Yatri Sathi/Normal Flow/on_update2.json
- TRV10/Yatri Sathi/Normal Flow/on_update3.json
- TRV10/Yatri Sathi/Normal Flow/search.json
- TRV10/Yatri Sathi/Normal Flow/select.json
- TRV10/Yatri Sathi/Normal Flow/track.json
- TRV10/Yatri Sathi/OTP Flow/confirm.json
- TRV10/Yatri Sathi/OTP Flow/init.json
- TRV10/Yatri Sathi/OTP Flow/on_confirm.json
- TRV10/Yatri Sathi/OTP Flow/on_init.json
- TRV10/Yatri Sathi/OTP Flow/on_search.json
- TRV10/Yatri Sathi/OTP Flow/on_track.json
- TRV10/Yatri Sathi/OTP Flow/on_update1.json
- TRV10/Yatri Sathi/OTP Flow/on_update2.json
- TRV10/Yatri Sathi/OTP Flow/on_update3.json
- TRV10/Yatri Sathi/OTP Flow/search.json
- TRV10/Yatri Sathi/OTP Flow/track.json
Yatri Saathi logs for Normal and Ride OTP Flow.
> Yatri Saathi logs

- logs/Xpressbees/IGM/01_issue.json
- logs/Xpressbees/IGM/02_on_issue.json
- logs/Xpressbees/IGM/03_unsolicited_on_issue_status.json
- logs/Xpressbees/IGM/04_issue_status.json
- logs/Xpressbees/IGM/05_on_issue_status.json
- logs/Xpressbees/IGM/06_issue_close.json
- We are working on 'RTO-Disposed' flow, will submit it in couple of days.
- Submitted IGM logs, Kindly review it.
> Xpressbees IGM logs

- B2B/Export-2.0.1/SignCatch/flow 1/confirm.json
- B2B/Export-2.0.1/SignCatch/flow 1/init.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_confirm.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_init.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_search.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_select.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_deliverd.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_out_for_delivery.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_packed.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_picked_up.json
- B2B/Export-2.0.1/SignCatch/flow 1/search.json
- B2B/Export-2.0.1/SignCatch/flow 1/select.json
- B2B/Export-2.0.1/SignCatch/flow 4/confirm.json
- B2B/Export-2.0.1/SignCatch/flow 4/init.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_confirm.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_init.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_search.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_select.json
- B2B/Export-2.0.1/SignCatch/flow 4/search.json
- B2B/Export-2.0.1/SignCatch/flow 4/select.json
> SignCatch verification logs for v2.0.1

- logs/CSC/Buyer with api.greenreciept.com/Flow2/confirm.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/init.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/log_report.md
- logs/CSC/Buyer with api.greenreciept.com/Flow2/on_cancel.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/on_confirm.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/on_init.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/on_search.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/on_select_non_serviceable.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/search.json
- logs/CSC/Buyer with api.greenreciept.com/Flow2/select_non_serviceable.json
- logs/CSC/Buyer with api.greenreciept.com/Flow4/on_update_approved.json
- logs/CSC/Buyer with api.greenreciept.com/Flow4/on_update_delivered.json
- logs/CSC/Buyer with api.greenreciept.com/Flow4/on_update_picked.json
Flow 2 - new order with seller cancel 
Flow 4 - return flow seller pending log update
> Retail Logs Flow Updates 

- logs/Xpressbees/RTO-Delivered/01_search.json
- logs/Xpressbees/RTO-Delivered/02_on_search.json
- logs/Xpressbees/RTO-Delivered/03_init.json
- logs/Xpressbees/RTO-Delivered/04_on_init.json
- logs/Xpressbees/RTO-Delivered/05_confirm.json
- logs/Xpressbees/RTO-Delivered/06_on_confirm.json
- logs/Xpressbees/RTO-Delivered/07_update.json
- logs/Xpressbees/RTO-Delivered/08_on_update.json
- logs/Xpressbees/RTO-Delivered/09_on_status_un_soliciated_in-progress_agent-assigned.json
- logs/Xpressbees/RTO-Delivered/10_on_status_un_soliciated_in-progress_order-picked-up.json
- logs/Xpressbees/RTO-Delivered/11_on_status_un_soliciated_in-progress_out-for-delivery.json
- logs/Xpressbees/RTO-Delivered/12_on_cancel_un_soliciated.json
- logs/Xpressbees/RTO-Delivered/13_on_status_un_soliciated_cancelled.json
- logs/Xpressbees/RTO-Delivered/14_on_status_un_soliciated_cancelled_rto_delivered.json
- logs/Xpressbees/RTO-Disposed/01_search.json
- logs/Xpressbees/RTO-Disposed/02_on_search.json
- logs/Xpressbees/RTO-Disposed/03_init.json
- logs/Xpressbees/RTO-Disposed/04_on_init.json
- logs/Xpressbees/RTO-Disposed/05_confirm.json
- logs/Xpressbees/RTO-Disposed/06_on_confirm.json
- logs/Xpressbees/RTO-Disposed/07_update.json
- logs/Xpressbees/RTO-Disposed/08_on_update.json
- logs/Xpressbees/RTO-Disposed/09_on_status_un_soliciated_in-progress_agent-assigned.json
- logs/Xpressbees/RTO-Disposed/10_on_status_un_soliciated_in-progress_order-picked-up.json
- logs/Xpressbees/RTO-Disposed/11_on_status_un_soliciated_in-progress_out-for-delivery.json
- logs/Xpressbees/RTO-Disposed/12_on_cancel_un_soliciated.json
- logs/Xpressbees/RTO-Disposed/13_on_status_un_soliciated_cancelled.json
- logs/Xpressbees/RTO-Disposed/14_on_status_un_soliciated_cancelled_rto_disposed.json
- Submitted RTO-Disposed and RTO-Delivered logs, Kindly review it.
> Xpressbees RTO-Disposed and RTO-Delivered logs

- TRV10/Namma Yatri/confirm.json
- TRV10/Namma Yatri/init.json
- TRV10/Namma Yatri/on_confirm.json
- TRV10/Namma Yatri/on_init.json
- TRV10/Namma Yatri/on_search.json
- TRV10/Namma Yatri/on_select.json
- TRV10/Namma Yatri/on_select2.json
- TRV10/Namma Yatri/on_update1.json
- TRV10/Namma Yatri/on_update2.json
- TRV10/Namma Yatri/on_update3.json
- TRV10/Namma Yatri/search.json
- TRV10/Namma Yatri/select.json
> Namma Yatri logs

- B2B/Export-2.0.1/SignCatch/flow 1/confirm.json
- B2B/Export-2.0.1/SignCatch/flow 1/init.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_init.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_search.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_select.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_deliverd.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_out_for_delivery.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_packed.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_picked_up.json
- B2B/Export-2.0.1/SignCatch/flow 1/on_status_proforma_invoice.json
- B2B/Export-2.0.1/SignCatch/flow 1/search.json
- B2B/Export-2.0.1/SignCatch/flow 1/select.json
- B2B/Export-2.0.1/SignCatch/flow 4/confirm.json
- B2B/Export-2.0.1/SignCatch/flow 4/init.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_confirm.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_init.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_search.json
- B2B/Export-2.0.1/SignCatch/flow 4/on_select.json
- B2B/Export-2.0.1/SignCatch/flow 4/search.json
- B2B/Export-2.0.1/SignCatch/flow 4/select.json
SC verification logs Export 2.0.1
> SC verification logs Export 2.0.1

- logs/Xpressbees/IGM/01_issue.json
- logs/Xpressbees/IGM/02_on_issue.json
- logs/Xpressbees/IGM/03_unsolicited_on_issue_status.json
- logs/Xpressbees/IGM/04_issue_status.json
- logs/Xpressbees/IGM/05_on_issue_status.json
- logs/Xpressbees/IGM/06_issue_close.json
- Resolved IGM issue and resubmitted logs, Kindly review it.
@bluecypher
> Xpressbees IGM: Resolved reported issue and resubmitted logs again.

- B2B/Export-2.0.1/Rapidor/flow 1/confirm.json
- B2B/Export-2.0.1/Rapidor/flow 1/init.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_confirm.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_init.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_search.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_select.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_status_Order-delivered.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_status_Order-picked-up.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_status_Out-for-delivery.json
- B2B/Export-2.0.1/Rapidor/flow 1/on_status_Pending.json
- B2B/Export-2.0.1/Rapidor/flow 1/search.json
- B2B/Export-2.0.1/Rapidor/flow 1/select.json
- B2B/Export-2.0.1/Rapidor/flow 4/init_2D.json
- B2B/Export-2.0.1/Rapidor/flow 4/init_reject.json
- B2B/Export-2.0.1/Rapidor/flow 4/on_init_2D.json
- B2B/Export-2.0.1/Rapidor/flow 4/on_init_reject.json
- B2B/Export-2.0.1/Rapidor/flow 4/on_search.json
- B2B/Export-2.0.1/Rapidor/flow 4/on_select.json
- B2B/Export-2.0.1/Rapidor/flow 4/search.json
- B2B/Export-2.0.1/Rapidor/flow 4/select.json
@SandeepGF Fixed the Gitguardian issues
> Rapidor - Export Logs for 2.0.1

- logs/Dailybee/Logistics/flow1/confirm.json
- logs/Dailybee/Logistics/flow1/init.json
- logs/Dailybee/Logistics/flow1/on_confirm.json
- logs/Dailybee/Logistics/flow1/on_init.json
- logs/Dailybee/Logistics/flow1/on_search.json
- logs/Dailybee/Logistics/flow1/on_status_out_for_delivery.json
- logs/Dailybee/Logistics/flow1/on_status_pending.json
- logs/Dailybee/Logistics/flow1/on_status_picked.json
- logs/Dailybee/Logistics/flow1/on_update.json
- logs/Dailybee/Logistics/flow1/search.json
- logs/Dailybee/Logistics/flow1/status.json
- logs/Dailybee/Logistics/flow2/init.json
- logs/Dailybee/Logistics/flow2/on_cancel.json
- logs/Dailybee/Logistics/flow2/on_init.json
- logs/Dailybee/Logistics/flow2/on_search.json
- logs/Dailybee/Logistics/flow2/on_status_pending.json
- logs/Dailybee/Logistics/flow2/on_status_rto_delivered.json
- logs/Dailybee/Logistics/flow2/on_status_rto_initiated.json
- logs/Dailybee/Logistics/flow2/on_update.json
- logs/Dailybee/Logistics/flow2/search.json
- logs/Dailybee/Logistics/flow2/status.json
- logs/Dailybee/Logistics/flow2/update.json
- logs/Dailybee/RSP/Flow 1 - no correction/on_receiver_recon.json
- logs/Dailybee/RSP/Flow 1 - no correction/receiver_recon.json
- logs/Dailybee/RSP/Flow 2 - with correction/on_receiver_recon.json
- logs/Dailybee/RSP/Flow 2 - with correction/receiver_recon.json
- logs/Dailybee/RSP/Flow 3 - Refund (Reverse Flow)/collector_recon.json
Updated the logs according to the comments on the below GitHub issue.
https://github.com/ONDC-Official/verification-logs/issues/1053
> Updated logistics & RSP logs as per compliance check

- logs/Dailybee/Logistics/flow1/confirm.json
- logs/Dailybee/Logistics/flow1/init.json
- logs/Dailybee/Logistics/flow1/on_confirm.json
- logs/Dailybee/Logistics/flow1/on_init.json
- logs/Dailybee/Logistics/flow1/on_search.json
- logs/Dailybee/Logistics/flow1/on_status_delivered.json
- logs/Dailybee/Logistics/flow1/on_status_out_for_delivery.json
- logs/Dailybee/Logistics/flow1/on_status_pending.json
- logs/Dailybee/Logistics/flow1/on_status_picked.json
- logs/Dailybee/Logistics/flow1/on_update.json
- logs/Dailybee/Logistics/flow1/search.json
- logs/Dailybee/Logistics/flow1/status.json
- logs/Dailybee/Logistics/flow1/update.json
- logs/Dailybee/Logistics/flow2/confirm.json
- logs/Dailybee/Logistics/flow2/init.json
- logs/Dailybee/Logistics/flow2/on_cancel.json
- logs/Dailybee/Logistics/flow2/on_confirm.json
- logs/Dailybee/Logistics/flow2/on_init.json
- logs/Dailybee/Logistics/flow2/on_search.json
- logs/Dailybee/Logistics/flow2/on_status_out_for_delivery.json
- logs/Dailybee/Logistics/flow2/on_status_pending.json
- logs/Dailybee/Logistics/flow2/on_status_pickedup.json
- logs/Dailybee/Logistics/flow2/on_status_rto_delivered.json
- logs/Dailybee/Logistics/flow2/on_update.json
- logs/Dailybee/Logistics/flow2/search.json
- logs/Dailybee/Logistics/flow2/status.json
- logs/Dailybee/Logistics/flow2/update.json
Address issues in compliance check: 
https://github.com/ONDC-Official/verification-logs/issues/1053
> Updated Logistics BAP logs as per compliance check.

- logs/Dailybee/Logistics/flow1/on_update.json
- logs/Dailybee/Logistics/flow1/update.json
Addresses: https://github.com/ONDC-Official/verification-logs/issues/1053
> Rectified Logistics BAP logs.

- logs/Xpressbees/RSP/basic-flow/01_receiver_recon.json
- logs/Xpressbees/RSP/basic-flow/02_on_receiver_recon.json
- logs/Xpressbees/RSP/correction-flow/01_receiver_recon.json
- logs/Xpressbees/RSP/correction-flow/02_on_receiver_recon.json
Submitted RSP logs, kindly review it.
@bluecypher
> xpressbees: rsp logs

- logs/Dailybee/Retail-Logs/Flow2/confirm.json
- logs/Dailybee/Retail-Logs/Flow2/init.json
- logs/Dailybee/Retail-Logs/Flow2/on_cancel.json
- logs/Dailybee/Retail-Logs/Flow2/on_confirm.json
- logs/Dailybee/Retail-Logs/Flow2/on_init.json
- logs/Dailybee/Retail-Logs/Flow2/on_search.json
- logs/Dailybee/Retail-Logs/Flow2/on_select.json
- logs/Dailybee/Retail-Logs/Flow2/on_select_non_serviceable.json
- logs/Dailybee/Retail-Logs/Flow2/on_status_pending.json
- logs/Dailybee/Retail-Logs/Flow2/search.json
- logs/Dailybee/Retail-Logs/Flow2/select.json
- logs/Dailybee/Retail-Logs/Flow2/select_non_serviceable.json
- logs/Dailybee/Retail-Logs/Flow2/status.json
- logs/Dailybee/Retail-Logs/Flow2/validations.log
Addressed the compliance check comments on logs: 
Issue:  https://github.com/ONDC-Official/verification-logs/issues/1030
> Dailybee: Updated Retail BPP logs as per compliance check. 28th September

- logs/airpay/rsp/order_payment_flow_27092023/collector_recon.json
- logs/airpay/rsp/order_payment_flow_27092023/on_collector_recon.json
- logs/airpay/rsp/order_payment_flow_27092023/on_receiver_recon.json
- logs/airpay/rsp/order_payment_flow_27092023/on_recon_status.json
- logs/airpay/rsp/order_payment_flow_27092023/on_settle.json
- logs/airpay/rsp/order_payment_flow_27092023/receiver_recon.json
- logs/airpay/rsp/order_payment_flow_27092023/recon_status.json
- logs/airpay/rsp/order_payment_flow_27092023/settle.json
Resubmitting logs for - Airpay (RSP) - compliance check (Issue #1003) Please review and confirm.
> Resubmitting logs for - Airpay (RSP) - compliance check (Issue #1003)

- logs/BuyNxt(All_Flow)/RSP-Moda_4/Receiver_Recon_1.json
- logs/BuyNxt(All_Flow)/RSP-Moda_4/on_receiver_recon_1.json
- logs/BuyNxt(All_Flow)/RSP-Moda_4/on_receiver_recon_2.json
- logs/BuyNxt(All_Flow)/RSP-Moda_4/on_receiver_recon_3.json
- logs/BuyNxt(All_Flow)/RSP-Moda_4/on_receiver_recon_4.json
- logs/BuyNxt(All_Flow)/RSP-Moda_4/on_receiver_recon_5.json
Here is the log for RSP(Modal 4) after feedback correction, Please review. Thanks.
> RSP_Modal_4(BuyNxt)

- logs/1bridge/rsf logs/correction flow/on_receiver_recon.json
- logs/1bridge/rsf logs/correction flow/receiver_recon.json
- logs/1bridge/rsf logs/successful flow/on_receiver_recon.json
- logs/1bridge/rsf logs/successful flow/receiver_recon.json
RSF logs for both success and correction flow. Seller NP: Rubanbridge Pvt. Ltd. (1bridge)
> RSF logs for Rubanbridge Pvt. Ltd. (1bridge)

- logs/1bridge/rsf logs/correction flow/on_receiver_recon.json
- logs/1bridge/rsf logs/correction flow/receiver_recon.json
- logs/1bridge/rsf logs/successful flow/on_receiver_recon.json
- logs/1bridge/rsf logs/successful flow/receiver_recon.json
RSF logs by 1bridge: fixed the incorrect values.
> 1bridge RSF logs: updated logs with correct values

- logs/BuyNxt(All_Flow)/RSP Log - One Order/Receiver_Recon.json
- logs/BuyNxt(All_Flow)/RSP Log - One Order/on_receiver_recon.json
After correction, added the logs. Please review.
> RSPLogs(Buynxt)

- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/confirm.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/init.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_confirm.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_init.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_search.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_select.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_status_deliverd.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_status_out_for_delivery.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_status_packed.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_status_picked_up.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/on_status_proforma_invoice.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/search.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 1/select.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/confirm.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/init.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/on_confirm.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/on_init.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/on_search.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/on_select.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/search.json
- B2B/Export-2.0.1/SignCatch_B2B_Domestic/flow 4/select.json
Verification logs for SignCatch B2B Domestic v2.0.1
> Verification logs for SignCatch B2B Domestic v2.0.1

- logs/ndhgo/igm/flow-1/issue.json
- logs/ndhgo/igm/flow-1/issue_close.json
- logs/ndhgo/igm/flow-1/issue_status.json
- logs/ndhgo/igm/flow-1/on_issue.json
- logs/ndhgo/igm/flow-1/on_issue_status.json
- logs/ndhgo/igm/flow-1/on_issue_status_unsolicited.json
- logs/ndhgo/igm/flow-2/issue.json
- logs/ndhgo/igm/flow-2/issue_close.json
- logs/ndhgo/igm/flow-2/issue_status.json
- logs/ndhgo/igm/flow-2/on_issue.json
- logs/ndhgo/igm/flow-2/on_issue_status.json
- logs/ndhgo/igm/flow-2/on_issue_status_unsolicited.json
- Added Flow 1 Logs
- Added Flow 2 Logs
> NDHGO - Seller App IGM logs

- logs/ndhgo/igm/flow-1/issue.json
- logs/ndhgo/igm/flow-1/issue_close.json
- logs/ndhgo/igm/flow-1/issue_status.json
- logs/ndhgo/igm/flow-1/on_issue.json
- logs/ndhgo/igm/flow-1/on_issue_status.json
- logs/ndhgo/igm/flow-1/on_issue_status_unsolicited.json
- logs/ndhgo/igm/flow-2/issue.json
- logs/ndhgo/igm/flow-2/issue_close.json
- logs/ndhgo/igm/flow-2/issue_status.json
- logs/ndhgo/igm/flow-2/on_issue.json
- logs/ndhgo/igm/flow-2/on_issue_status.json
- logs/ndhgo/igm/flow-2/on_issue_status_unsolicited.json
> NDHGO - BPP IGM Logs Revised

- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/confirm.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/init.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_confirm.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_init.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_search.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_select.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_delivered.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_payment.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_picked.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_transit.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/search.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/select.json
- B2B/Export-2.0.2/Ninjacart_Buyer/NON_RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/status.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/confirm.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/init.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_confirm.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_init.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_search.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_select.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_delivered.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_payment.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_picked.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/on_status_transit.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/search.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/select.json
- B2B/Export-2.0.2/Ninjacart_Buyer/RFQ_FLOW/Flow 2 Seller_Prepaid_Payment/status.json
> Ninjacart buyer Seller accepting prepaid payment logs

- TRV11/NammaYatri/Flow 3/confirm_cancel.json
- TRV11/NammaYatri/Flow 3/confirm_on_cancel.json
- TRV11/NammaYatri/Flow 3/soft_cancel.json
- TRV11/NammaYatri/Flow 3/soft_on_cancel.json
Added Cancellation Flow logs for Namma-Yatri.
> TRV11: NammaYatri - Added Cancellation Flow Logs

- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/confirm.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/init.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/on_confirm.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/on_init.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/on_search_1.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/on_search_2.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/on_select.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/on_status.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/search_1.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/search_2.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/select.json
- TRV11/Vaipratech/Flow 1 (STATION-CODE-FLOW)/status.json
- TRV11/Vaipratech/Flow 2 (USER-CANCEL-FLOW)/cancel_1 (SOFT_CANCEL).json
- TRV11/Vaipratech/Flow 2 (USER-CANCEL-FLOW)/cancel_2 (CONFIRM_CANCEL).json
- TRV11/Vaipratech/Flow 2 (USER-CANCEL-FLOW)/on_cancel_1.json
- TRV11/Vaipratech/Flow 2 (USER-CANCEL-FLOW)/on_cancel_2.json
Submitting updated metro logs for the TRV11 domain.
> Vaipratech logs

- B2B/Export-2.0.2/PX/buyer/RET10/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET10/search.json
- B2B/Export-2.0.2/PX/buyer/RET12/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET12/search.json
- B2B/Export-2.0.2/PX/buyer/RET13/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET13/search.json
- B2B/Export-2.0.2/PX/buyer/RET14/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET14/search.json
- B2B/Export-2.0.2/PX/buyer/RET15/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET15/search.json
- B2B/Export-2.0.2/PX/buyer/RET16/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET16/search.json
- B2B/Export-2.0.2/PX/buyer/RET1A/on_search.json
- B2B/Export-2.0.2/PX/buyer/RET1A/search.json
- B2B/Export-2.0.2/PX/buyer/RET1B/search.json
- B2B/Export-2.0.2/PX/buyer/RET1C/search.json
- B2B/Export-2.0.2/PX/buyer/RET1D/search.json
Search/on_search for registered domains
> ONDC Tech Logs - BAP

- TRV11/DMRC/RSF/Flow 1/on_receiver_recon.json
- TRV11/DMRC/RSF/Flow 1/receiver_recon.json
- TRV11/DMRC/RSF/Flow 2 (Correction)/on_receiver_recon.json
- TRV11/DMRC/RSF/Flow 2 (Correction)/receiver_recon.json
Submitting RSF Tech Logs for Verification
> RSF Logs (DMRC)

- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/confirm.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/init.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/on_cancel.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/on_confirm.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/on_init.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/on_search.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/on_select.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/on_status.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/search.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/select.json
- logs/Earnest BAP(TSP)(GC v2)/FLOW 3/status.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/confirm.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/init.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/on_confirm.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/on_init.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/on_search.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/on_select.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/on_status.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/search.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/select.json
- logs/Earnest BAP(TSP)(GC v2)/Flow 1/status.json
@Rishabh-ondc can you please review the logs.
> log submission for Earnest BAP TSP util (GC v2, flow 1 and flow 3)

- TRV11/Chalo/flow-3/on_receiver_recon.json
- TRV11/Chalo/flow-3/on_receiver_recon_correction.json
- TRV11/Chalo/flow-3/receiver_recon.json
- TRV11/Chalo/flow-3/receiver_recon_correction.json
Removed RSF logs from [this](https://github.com/ONDC-Official/verification-logs/pull/1567) PR and raised a separate PR for them.
> Added RSF logs

- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/issue (close).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/issue (open).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/on_issue.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/on_issue_status.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/issue (close).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/issue (open).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/on_issue.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/on_issue_status.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/issue (close).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/issue (open).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/on_issue.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/on_issue_status.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/issue (close).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/issue (open).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/on_issue.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/on_issue_status.json
IGM logs for both buyer and seller
> ONDC IGM Tech Logs - NEW

- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/issue (close).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/issue (open).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/issue_status.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/on_issue.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/on_issue_status(UNSOLICITED).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Fulfillment/on_issue_status.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/issue (close).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/issue (open).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/issue_status.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/on_issue.json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/on_issue_status(UNSOLICITED).json
- B2B/Export-2.0.2/PX/buyer/IGM Logs/Item/on_issue_status.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/issue (close).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/issue (open).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/issue_status.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/on_issue.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/on_issue_status(UNSOLICITED).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Fulfillment/on_issue_status.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/issue (close).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/issue (open).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/issue_status.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/on_issue.json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/on_issue_status(UNSOLICITED).json
- B2B/Export-2.0.2/PX/seller/IGM Logs/Item/on_issue_status.json
IGM logs for both buyer and seller
> ONDC IGM Tech Logs - UPDATE

- logs/StelCoreLogs/RET12_logs/on_search.json
- logs/StelCoreLogs/RET12_logs/search.json
Logs for fashion domain RET:12
> RET:12 Logs

- B2B/Channelier/SearchPayloads/Appliances/on_search.json
- B2B/Channelier/SearchPayloads/Appliances/search.json
- B2B/Channelier/SearchPayloads/BPC/on_search.json
- B2B/Channelier/SearchPayloads/BPC/search.json
- B2B/Channelier/SearchPayloads/Electronics/on_search.json
- B2B/Channelier/SearchPayloads/Electronics/search.json
- B2B/Channelier/SearchPayloads/Fashion/on_search.json
- B2B/Channelier/SearchPayloads/Fashion/search.json
- B2B/Channelier/SearchPayloads/Home and Kitchen/on_search.json
- B2B/Channelier/SearchPayloads/Home and Kitchen/search.json
…Appliances RET15, Home & Kitchen RET16
> Channelier B2B updated logs for Fashion RET12, BPC RET13, Electronics RET14, Appliances RET15, Home & Kitchen RET16

- TRV11/Uber/Flow1/confirm.json
- TRV11/Uber/Flow1/init.json
- TRV11/Uber/Flow1/on_confirm.json
- TRV11/Uber/Flow1/on_init.json
- TRV11/Uber/Flow1/on_search_1.json
- TRV11/Uber/Flow1/on_search_2.json
- TRV11/Uber/Flow1/on_status.json
- TRV11/Uber/Flow1/search_1.json
- TRV11/Uber/Flow1/search_2.json
- TRV11/Uber/Flow1/status.json
- TRV11/Uber/Flow2/cancel_1.json
- TRV11/Uber/Flow2/cancel_2.json
- TRV11/Uber/Flow2/confirm.json
- TRV11/Uber/Flow2/init.json
- TRV11/Uber/Flow2/on_cancel_1.json
- TRV11/Uber/Flow2/on_cancel_2.json
- TRV11/Uber/Flow2/on_confirm.json
- TRV11/Uber/Flow2/on_init.json
- TRV11/Uber/Flow2/on_search_1.json
- TRV11/Uber/Flow2/on_search_2.json
- TRV11/Uber/Flow2/search_1.json
- TRV11/Uber/Flow2/search_2.json
Log testing for Uber buyer metro app
> Log testing for Uber buyer metro app

- TRV11/Uber/RSF/Flow 1/on_receiver_recon.json
- TRV11/Uber/RSF/Flow 1/receiver_recon.json
- TRV11/Uber/RSF/Flow 2 Correction Flow/on_receiver_recon.json
- TRV11/Uber/RSF/Flow 2 Correction Flow/receiver_recon.json
RSF log testing for Uber buyer metro app
> RSF log testing for Uber buyer metro app

- TRV11/Uber/IGM/issue_1.json
- TRV11/Uber/IGM/issue_2.json
- TRV11/Uber/IGM/issue_status.json
- TRV11/Uber/IGM/on_issue_1.json
- TRV11/Uber/IGM/on_issue_status.json
IGM log testing for Uber buyer metro app
> IGM log testing for Uber buyer metro app

- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/1.Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/10.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/11.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/12.Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/13.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/14.Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/2.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/3.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/6.Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/7.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/8.On_Issue.json
- SRV/SRV17/CRISP/IGM/Buyer raises a complaint for item category Flow 1/9,Issue.json
> IGM 2.0 first flow

- logs/Earnest BAP(TSP)(GC v2)/IGM/issue(closing).json
- logs/Earnest BAP(TSP)(GC v2)/IGM/issue.json
- logs/Earnest BAP(TSP)(GC v2)/IGM/issue_status.json
- logs/Earnest BAP(TSP)(GC v2)/IGM/on_issue.json
- logs/Earnest BAP(TSP)(GC v2)/IGM/on_issue_status(seller action).json
- logs/Earnest BAP(TSP)(GC v2)/IGM/on_issue_status.json
IGM logs for TSP built by Earnest for GC use case
@Rishabh-ondc can you please review the logs.
> feat: Earnest ISP IGM logs

- TRV11/fasttrack/RSF 1.0/Flow1/on_receiver_recon.json
- TRV11/fasttrack/RSF 1.0/Flow1/receiver_recon.json
- TRV11/fasttrack/RSF 1.0/Flow2-Correction/on_receiver_recon.json
- TRV11/fasttrack/RSF 1.0/Flow2-Correction/receiver_recon.json
Added logs for TRV11 RSF1.0 flow
> Added Rsf 1.0 logs for TRV11
